export const actionType={
        SET_PRODUCTS:"SET_PRODUCTS",
        GET_NUMBER_CART:"GET_NUMBER_CART",
        ADD_CART:"ADD_CART",
        UPDATE_CART:"UPDATE_CART",
        DELETE_CART:"DELETE_CART",
        INCREASE_QUANTITY:"INCREASE_QUANTITY",
        DECREASE_QUANTITY:"DECREASE_QUANTITY",
        SET_LOGIN_STATUS: "SET_LOGIN_STATUS"
}